# Generated by Django 6.0.1 on 2026-02-01 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='location_text',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_trip',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sent_by',
        ),
        migrations.AddField(
            model_name='schedule',
            name='default_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.driver'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='default_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.vehicle'),
        ),
        migrations.AlterField(
            model_name='currentlocation',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='mainapp.dailytrip'),
        ),
        migrations.AlterField(
            model_name='dailytrip',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In-Progress', 'In-Progress'), ('Delayed', 'Delayed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='est_minutes',
            field=models.IntegerField(help_text='Estimated minutes from start'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='days_of_week',
            field=models.CharField(max_length=50),
        ),
    ]
