# Generated by Django 6.0.1 on 2026-02-01 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_incident_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.stop'),
        ),
    ]
